/*package webTest;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ComprarCursoG {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void comprarCursodeGraca() {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1440, 779));
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();
        driver.findElement(By.cssSelector(".no-link-style:nth-child(3) > .img-wrapper > .bg-img")).click();
        js.executeScript("window.scrollTo(0,0)");
        js.executeScript("window.scrollTo(0,48)");
        driver.findElement(By.linkText("Comprar")).click();
        js.executeScript("window.scrollTo(0,0)");
      //  assertEquals("Java em poucos passos",driver.findElement(By.cssSelector("h1")).getText());
        driver.findElement(By.id("seu nome completo-i-21357129893928856")).click();
        driver.findElement(By.id("seu nome completo-i-21357129893928856")).sendKeys("Eva Souza");
        driver.findElement(By.id("seu email-i-5724621959697925")).sendKeys("evaluzia.souza@gmail.com");
        driver.findElement(By.id("confirme seu email-i-645787309216388")).click();
        driver.findElement(By.id("confirme seu email-i-645787309216388")).sendKeys("evaluzia.souza@gmail.com");
        driver.findElement(By.cssSelector(".icon-right")).click();
        driver.findElement(By.id("senha-i-9318387629543984")).sendKeys("asD#89447182");
        driver.findElement(By.id("senha-i-9318387629543984")).click();
        driver.findElement(By.id("senha-i-9318387629543984")).click();
        driver.findElement(By.id("senha-i-9318387629543984")).click();
        {
            WebElement element = driver.findElement(By.id("senha-i-9318387629543984"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("senha-i-9318387629543984")).click();
        driver.findElement(By.cssSelector(".button-text > span")).click();
        driver.findElement(By.cssSelector(".radio-selected")).click();
        driver.findElement(By.cssSelector(".button-text > span > span")).click();
    }
}
*/