package webTest;
// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class ComprarCurso {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void comprarCursoCartao() throws InterruptedException {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1440, 779));
        driver.findElement(By.linkText("Começar Agora")).click();
        assertEquals("Todos cursos", driver.findElement(By.cssSelector("h1")).getText());
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".no-link-style:nth-child(2) > .img-wrapper > .bg-img")).click();
        js.executeScript("window.scrollTo(0,0)");
        js.executeScript("window.scrollTo(0,48)");
        Thread.sleep(10000);
        assertEquals("Pacote de cursos", driver.findElement(By.cssSelector("h1")).getText());
        Thread.sleep(10000);
        driver.findElement(By.linkText("Comprar")).click();
        js.executeScript("window.scrollTo(0,0)");
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".fa-circle")).click();
        assertThat(driver.findElement(By.cssSelector(".radio-selected")).getText(), is("Já tenho uma conta"));
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("input[type=email]")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("input[type=email]")).sendKeys("evaluzia.souza@gmail.com");
        Thread.sleep(6000);
        {
            WebElement element = driver.findElement(By.cssSelector("input[type=password]"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asD#89447182");
        Thread.sleep(10000);
        {
            WebElement element = driver.findElement(By.cssSelector(".button-text > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".button-text > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".button-text > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".button-text > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".desktop-header .desktop-logo")).click();
        Thread.sleep(10000);
        {
            WebElement element = driver.findElement(By.linkText("Meus Cursos"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".user-avatar > p")).click();
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".dropdown_footer")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".swal2-confirm"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        Thread.sleep(10000);
        driver.findElement(By.cssSelector(".swal2-confirm")).click();
        driver.findElement(By.cssSelector(".button-text > span")).click();
        driver.findElement(By.cssSelector("#content-card .fas")).click();
        Thread.sleep(20000);
        driver.findElement(By.cssSelector(".radio-selected")).click();
        driver.findElement(By.cssSelector(".button-radio-options > button:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".button-text > span > span")).click();
        Thread.sleep(20000);
        driver.findElement(By.cssSelector("#content-card .fas")).click();
    }
}
