package webTest;
// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class ConsultarCursos {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void consultarCursos() throws InterruptedException {
        driver.get("https://testando.eveclass.com/pt/conta/meus-cursos");
        driver.manage().window().setSize(new Dimension(1400, 760));
        driver.findElement(By.cssSelector("input[type=email]")).click();
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("input[type=email]")).sendKeys("evaluzia.souza@gmail.com");
        Thread.sleep(6000);
        driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asD#89447182");
        driver.findElement(By.cssSelector(".button-text > span")).click();
        Thread.sleep(20000);
        driver.findElement(By.cssSelector(".account-sibebar-nav-item_selected .account-sibebar-nav-item-title")).click();
        driver.findElement(By.cssSelector(".section:nth-child(1) > .header")).click();
    }
}
