/*package webTest;


// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class Teste {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testandoEveclass2() {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1440, 779));
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        assertThat(driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).getText(), is("Entrar"));
        driver.get("https://testando.eveclass.com/pt/auth/entrar");
        driver.findElement(By.cssSelector("input[type=email]")).sendKeys("evaluzia.souza@gmail.com");
        driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asD#89447182");
        driver.findElement(By.cssSelector(".auth-header > p:nth-child(3)")).click();
    //    assertThat(driver.findElement(By.cssSelector(".button-text > span")).getText(), is("Entrar"));
    //    driver.findElement(By.cssSelector(".button-text > span")).click();

        driver.get("https://testando.eveclass.com/pt/admin/conteudo?s=y");
            driver.manage().window().setSize(new Dimension(1440, 779));

          driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        assertThat(driver.findElement(By.cssSelector(".ACTIVITY .text-title")).getText(), is("Atividades"));
        driver.findElement(By.cssSelector(".ACTIVITY .text-title")).click();
    /*    driver.findElement(By.cssSelector(".button:nth-child(3) > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".button:nth-child(3) > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("name-i-44653983065499883")).click();
        driver.findElement(By.id("name-i-44653983065499883")).sendKeys("Teste X");
        driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".alert:nth-child(1) > .alert-text > div:nth-child(1)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
    }
}*/







 /*

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AlterarAtividade {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testandoEveclass() {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1440, 779));
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        assertThat(driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).getText(), is("Entrar"));
        driver.get("https://testando.eveclass.com/pt/auth/entrar");
        driver.findElement(By.cssSelector("input[type=email]")).click();
        driver.findElement(By.cssSelector("input[type=email]")).sendKeys("evaluzia.souza@gmail.com");
        driver.findElement(By.cssSelector("input[type=password]")).click();
        driver.findElement(By.cssSelector("input[type=password]")).sendKeys("asD#89447182");
        driver.findElement(By.cssSelector(".auth-header > p:nth-child(3)")).click();
        assertThat(driver.findElement(By.cssSelector(".auth-header > p:nth-child(3)")).getText(), is("Insira seu email e senha de acesso."));

        assertThat(driver.findElement(By.cssSelector(".button-text > span")).getText(), is("Entrar"));
        driver.findElement(By.cssSelector(".button-text > span")).click();
        driver.get("https://testando.eveclass.com/pt/admin/conteudo");
       // assertEquals("Visão Geral",driver.findElement(By.cssSelector("h1")).getText());
        driver.findElement(By.id("context-admin")).click();
        assertThat(driver.findElement(By.cssSelector(".ACTIVITY .text-title")).getText(), is("Atividades"));

        driver.findElement(By.cssSelector(".ACTIVITY .text-title")).click();
        new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.elementToBeClickable(By.xpath("text-title")));

        driver.findElement(By.cssSelector(".list-item:nth-child(1) .list-item-desc-badges")).click();
        driver.findElement(By.cssSelector(".button:nth-child(5) > .button-text > span > span")).click();

        {
            WebElement element = driver.findElement(By.cssSelector(".button:nth-child(5) > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("name-i-7083609499520493")).click();
        driver.findElement(By.id("name-i-7083609499520493")).sendKeys("Teste de Selenium");
        driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".select:nth-child(2) .msg"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
    }
}
*/


